// JsFromRoutes CacheKey 0cb59a980254b598ab4a9d9c20413453
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as dashboard } from '~/api/DashboardApi'
export { default as usersPasswords } from '~/api/Users/PasswordsApi'
export { default as usersRegistrations } from '~/api/Users/RegistrationsApi'
export { default as usersSessions } from '~/api/Users/SessionsApi'
