// JsFromRoutes CacheKey fea1b34dc4fa17c8d3ddc2b8d6775db3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/'),
}
