// JsFromRoutes CacheKey 8377bd7b84a31517069a7f7a604b0e49
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  cancel: definePathHelper('get', '/users/cancel'),
  new: definePathHelper('get', '/users/sign_up'),
  edit: definePathHelper('get', '/users/edit'),
  update: definePathHelper('patch', '/users'),
  destroy: definePathHelper('delete', '/users'),
  create: definePathHelper('post', '/users'),
}
